version: '3.9'

services:

    nginx:
        image: nginx:latest
        container_name: nginx
        environment:
            - VIRTUAL_HOST=127.0.0.1
        depends_on:
            - php
        volumes:
            - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/
        networks:
            - frontend
            - backend

    php:
        build:
            context: ./docker/php
        volumes:
            - .:/var/www/html/
        networks:
            - backend

networks:
    frontend:
        external:
            name: proxy_proxy
    backend:
